### ISSUE TITLE
Implement Cantaloupe image server

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/arclight_integration_project#7]
Dates are very much an estimate. Probably less important to start this immediately, as we don't have a process to create manifests or any test objects on disk first, but you can get it set up/installed.

**Comment by kmules1** [comment]
- location: /opt/cantaloupe/cantaloupe-5.0.6
- Apache configured:
    -  /iiif : base path for Cantaloupe proper
    - /admin : admin page for Cantaloupe (credentials until shibboleth configured)
    - /meta : direct path to files (necessary for accessing non-image data)
- need subdomain and SSL for shibboleth
